---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-app
  labels:
    app: ace-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ace-app
  template:
    metadata:
      labels:
        app: ace-app
    spec:
      containers:
      - name: pandacloud-container
        image: 571600846070.dkr.ecr.ap-south-1.amazonaws.com/amazon-prime:latest
        ports:
        - containerPort: 3000
...
